name:                aoc2019
version:             0.1.0.0
github:              "valeksenko/aoc2019"
license:             BSD3
author:              "Val Aleksenko"
maintainer:          "v.aleksenko@gmail.com"
copyright:           "2019 Val Aleksenko"

extra-source-files:
- README.md
- Notes.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/valeksenko/aoc2019#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- array
- vector
- sbv
- search-algorithms
- random
- data-ordlist
- digits
- extra
- split

library:
  source-dirs: src

executables:
  aoc2019-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc2019
    - containers
    - array
    - vector
    - sbv
    - random
    - gloss

tests:
  aoc2019-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc2019
    - tasty
    - tasty-hunit
    - tasty-quickcheck
    - QuickCheck


benchmarks:
  aoc2019-bench:
    main:                Main.hs
    source-dirs:         bench
    ghc-options:
    - -threaded
    dependencies:
    - aoc2019
    - criterion